### ISSUE TITLE
Invalid tip

### ISSUE THREAD

**Issue by Rovak** [WietseWind/xrptipbot#4]
Tweet https://twitter.com/Razko/status/1033382791088680960 was recognized as an attempt to tip although there weren't any `<user> +<amount> @xrptipbot` expressions present in the tweet

**Comment by WietseWind** [comment]
Hey! Thanks for the headsup! I actually changed the regexp to allow this kind of tips (formatting) many months ago because I received many DM's from people wondering why their tip didn't go trough. Eg.

`Hey @someuser, thank you very very much +1 for the stuff you did - @xrptipbot`

... So the bot looks for:

1. A mention of someone else
2. A `\+[ ]*[0-9\.,]+` match
3. A mention of the TipBot

**Comment by Rovak** [comment]
Ah that makes sense, thanks for the clarification
